### ISSUE TITLE
[BUG] Performance issue

### ISSUE THREAD

**Issue by RAPHAEL599** [CptbeffHeart/DeepStorage#14]
![image](https://github.com/CptbeffHeart/DeepStorage/assets/73084300/7863fee6-6124-4fda-a9d9-6652e2f3a278)
[latest (5).log](https://github.com/user-attachments/files/16042380/latest.5.log)

**Comment by RAPHAEL599** [comment]
https://www.youtube.com/watch?v=uEKKuOTdFCo&ab_channel=RAPHAEL599

**Comment by CptbeffHeart** [comment]
Yes i noticed performance issue
I'm investigating

**Comment by RAPHAEL599** [comment]
Any news?

**Comment by CptbeffHeart** [comment]
In progress
